# install.packages("forcats")
# install.packages("ggplot2")
# install.packages("lubridate")
# install.packages("readr")
# install.packages("shiny")
# install.packages("tibble")
# install.packages("tidyr")
# install.packages("zoo")
# install.packages("shiny")
# install.packages("shinyWidgets")
# install.packages("shinydashboardPlus")
# install.packages("shinydashboard")
# install.packages("lubridate")
# install.packages("dplyr")
install.packages("remotes")
remotes::install_github("TheZetner/cases")
